USE book_store;
GO

-- ======================================================
-- PROCEDURE 1: AUTH - Register (Customer + Member)
-- ======================================================
CREATE OR ALTER PROCEDURE sp_DangKyThanhVien
    @ho NVARCHAR(100),
    @ho_ten_dem NVARCHAR(200),
    @email NVARCHAR(200),
    @sdt NVARCHAR(20),
    @ten_dang_nhap NVARCHAR(100),
    @mat_khau NVARCHAR(200), -- Hash this in Go!
    @gioi_tinh NVARCHAR(10) = 'Khac',
    @ngay_sinh DATE = NULL
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;

        -- 1. Check Duplicates
        IF EXISTS (SELECT 1 FROM thanh_vien WHERE ten_dang_nhap = @ten_dang_nhap)
            THROW 50030, N'Tên đăng nhập đã tồn tại', 1;
            
        IF EXISTS (SELECT 1 FROM khach_hang WHERE email = @email)
            THROW 50031, N'Email đã được sử dụng', 1;

        -- 2. Insert Base Customer
        INSERT INTO khach_hang (ho_ten_dem, ho, ngay_sinh, email, sdt)
        VALUES (@ho_ten_dem, @ho, @ngay_sinh, @email, @sdt);

        DECLARE @new_kh_id INT = SCOPE_IDENTITY();

        -- 3. Insert Member Credentials
        INSERT INTO thanh_vien (ma_khach_hang, ten_dang_nhap, mat_khau_ma_hoa, gioi_tinh)
        VALUES (@new_kh_id, @ten_dang_nhap, @mat_khau, @gioi_tinh);

        COMMIT TRANSACTION;
        
        -- Return the new ID
        SELECT @new_kh_id AS ma_khach_hang;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO

-- ======================================================
-- PROCEDURE 2: AUTH - Login
-- ======================================================
CREATE OR ALTER PROCEDURE sp_DangNhap
    @ten_dang_nhap NVARCHAR(100),
    @mat_khau NVARCHAR(200)
AS
BEGIN
    SET NOCOUNT ON;
    
    DECLARE @id INT;
    SELECT @id = ma_khach_hang 
    FROM thanh_vien 
    WHERE ten_dang_nhap = @ten_dang_nhap AND mat_khau_ma_hoa = @mat_khau;

    IF @id IS NULL THROW 50035, N'Sai tên đăng nhập hoặc mật khẩu', 1;

    -- Return Basic Info
    SELECT tv.ma_khach_hang, tv.ten_dang_nhap, kh.ho + ' ' + kh.ho_ten_dem as ho_ten
    FROM thanh_vien tv
    JOIN khach_hang kh ON tv.ma_khach_hang = kh.ma_khach_hang
    WHERE tv.ma_khach_hang = @id;
END;
GO

-- ======================================================
-- [NEW] CREATE GUEST SESSION
-- Logic: 
--   1. Generate a unique dummy email (to satisfy Unique Constraint).
--   2. Insert into khach_hang (Base Table).
--   3. Insert into khach (Guest Table).
-- ======================================================
CREATE OR ALTER PROCEDURE sp_TaoSessionKhach
    @ma_session NVARCHAR(200), -- Generated by Backend (UUID)
    @ma_khach_hang INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;

        -- 1. Create Unique Dummy Email
        -- Format: guest_SESSIONID@bookstore.local
        DECLARE @DummyEmail NVARCHAR(200) = 'guest_' + @ma_session + '@bookstore.local';

        -- 2. Insert Base Customer (Placeholder Data)
        INSERT INTO khach_hang (ho_ten_dem, ho, email, sdt, ngay_sinh)
        VALUES (N'Khách', N'Vãng Lai', @DummyEmail, '', NULL);

        SET @ma_khach_hang = SCOPE_IDENTITY();

        -- 3. Insert Guest Record
        INSERT INTO khach (ma_khach_hang, ma_session)
        VALUES (@ma_khach_hang, @ma_session);

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO

-- ======================================================
-- PROC 3: sp_ThemSach (CLEAN VERSION)
-- ======================================================
CREATE OR ALTER PROCEDURE sp_ThemSach
    @ten_sach NVARCHAR(200),
    @nam_xuat_ban INT,
    @ma_nxb INT,
    @so_trang INT,
    @ngon_ngu NVARCHAR(50),
    @trong_luong DECIMAL(10,2) = NULL,
    @do_tuoi INT = NULL,
    @hinh_thuc NVARCHAR(50) = NULL,
    @mo_ta NVARCHAR(MAX) = NULL,
    @ten_nguoi_dich NVARCHAR(200) = NULL,
    @gia_ban MONEY, 
    @ma_sach_moi INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;
        
        -- [LOGIC ONLY - Validations handled by Triggers/Constraints]
        
        -- 1. Insert Book
        INSERT INTO sach (
            ten_sach, nam_xuat_ban, ma_nxb, so_trang, ngon_ngu,
            trong_luong, do_tuoi, hinh_thuc, mo_ta, ten_nguoi_dich,
            gia_hien_tai, ma_gia_hien_tai, 
            so_sao_trung_binh, tong_so_danh_gia, ma_rating_hien_tai,
            da_xoa
        )
        VALUES (
            @ten_sach, @nam_xuat_ban, @ma_nxb, @so_trang, @ngon_ngu,
            @trong_luong, @do_tuoi, @hinh_thuc, @mo_ta, @ten_nguoi_dich,
            @gia_ban, NULL, 
            0, 0, NULL,     
            0
        );
        
        SET @ma_sach_moi = SCOPE_IDENTITY();
        
        -- 2. Create Initial Price History (Trigger checks @gia_ban here)
        INSERT INTO gia_ban (ma_sach, gia) VALUES (@ma_sach_moi, @gia_ban);
        DECLARE @pid INT = SCOPE_IDENTITY();

        -- 3. Create Initial Rating History
        INSERT INTO tong_hop_danh_gia (ma_sach, diem_trung_binh, tong_luot_danh_gia) 
        VALUES (@ma_sach_moi, 0, 0);
        DECLARE @rid INT = SCOPE_IDENTITY();

        -- 4. Wire up Pointers
        UPDATE sach 
        SET ma_gia_hien_tai = @pid, ma_rating_hien_tai = @rid
        WHERE ma_sach = @ma_sach_moi;
        
        -- 5. Init Inventory
        DECLARE @ma_kho_mac_dinh INT = (SELECT TOP 1 ma_kho FROM kho ORDER BY ma_kho);
        IF @ma_kho_mac_dinh IS NOT NULL
            INSERT INTO so_luong_sach_kho (ma_kho, ma_sach, so_luong_ton)
            VALUES (@ma_kho_mac_dinh, @ma_sach_moi, 0);
        
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK;
        THROW;
    END CATCH
END;
GO

-- ======================================================
-- PROC 4: sp_SuaSach (CLEAN VERSION)
-- ======================================================
CREATE OR ALTER PROCEDURE sp_SuaSach
    @ma_sach INT,
    @ten_sach NVARCHAR(200) = NULL,
    @nam_xuat_ban INT = NULL,
    @ma_nxb INT = NULL,
    @so_trang INT = NULL,
    @ngon_ngu NVARCHAR(50) = NULL,
    @trong_luong DECIMAL(10,2) = NULL,
    @do_tuoi INT = NULL,
    @hinh_thuc NVARCHAR(50) = NULL,
    @mo_ta NVARCHAR(MAX) = NULL,
    @ten_nguoi_dich NVARCHAR(200) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        -- Triggers will validate the data update automatically
        UPDATE sach
        SET 
            ten_sach = ISNULL(@ten_sach, ten_sach),
            nam_xuat_ban = ISNULL(@nam_xuat_ban, nam_xuat_ban),
            ma_nxb = ISNULL(@ma_nxb, ma_nxb),
            so_trang = ISNULL(@so_trang, so_trang),
            ngon_ngu = ISNULL(@ngon_ngu, ngon_ngu),
            trong_luong = ISNULL(@trong_luong, trong_luong),
            do_tuoi = ISNULL(@do_tuoi, do_tuoi),
            hinh_thuc = ISNULL(@hinh_thuc, hinh_thuc),
            mo_ta = ISNULL(@mo_ta, mo_ta),
            ten_nguoi_dich = ISNULL(@ten_nguoi_dich, ten_nguoi_dich)
        WHERE ma_sach = @ma_sach;
    END TRY
    BEGIN CATCH
        THROW;
    END CATCH
END;
GO

-- ======================================================
-- PROC 5: sp_CapNhatGia (CLEAN VERSION)
-- ======================================================
CREATE OR ALTER PROCEDURE sp_CapNhatGia
    @ma_sach INT,
    @gia_moi MONEY
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;

        -- 1. Add to History (Trigger checks @gia_moi here)
        INSERT INTO gia_ban (ma_sach, gia) VALUES (@ma_sach, @gia_moi);
        DECLARE @new_price_id INT = SCOPE_IDENTITY();

        -- 2. Update Cache & Pointer
        UPDATE sach 
        SET gia_hien_tai = @gia_moi, ma_gia_hien_tai = @new_price_id 
        WHERE ma_sach = @ma_sach;

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK;
        THROW;
    END CATCH
END;
GO

-- ======================================================
-- PROCEDURE: Add OR Update Rating (Upsert)
-- Logic: 
--   1. Check if user already reviewed this book.
--   2. If YES -> UPDATE the existing row (Stars, Content, Date).
--   3. If NO  -> INSERT a new row.
--   4. Triggers will still run to calculate average stars.
-- ======================================================
CREATE OR ALTER PROCEDURE sp_ThemDanhGia
    @ma_sach INT,
    @ma_khach_hang INT,
    @so_sao INT,
    @noi_dung NVARCHAR(MAX)
AS
BEGIN
    SET NOCOUNT ON;

    -- Check if a review already exists for this User + Book
    IF EXISTS (SELECT 1 FROM danh_gia WHERE ma_sach = @ma_sach AND ma_khach_hang = @ma_khach_hang)
    BEGIN
        -- [UPDATE] Overwrite the old review
        UPDATE danh_gia
        SET so_sao = @so_sao,
            noi_dung = @noi_dung,
            ngay_danh_gia = GETDATE() -- Refresh the timestamp
        WHERE ma_sach = @ma_sach AND ma_khach_hang = @ma_khach_hang;
    END
    ELSE
    BEGIN
        -- [INSERT] Create new review
        INSERT INTO danh_gia (ma_sach, ma_khach_hang, so_sao, noi_dung, ngay_danh_gia)
        VALUES (@ma_sach, @ma_khach_hang, @so_sao, @noi_dung, GETDATE());
    END
END;
GO

-- ======================================================
-- PROCEDURE 7: sp_XoaSach (Soft Delete)
-- ======================================================
CREATE OR ALTER PROCEDURE sp_XoaSach
    @ma_sach INT
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        UPDATE sach SET da_xoa = 1 WHERE ma_sach = @ma_sach;
    END TRY
    BEGIN CATCH
        THROW;
    END CATCH
END;
GO

-- ======================================================
-- PROCEDURE 9: Get Reviews
-- ======================================================
CREATE OR ALTER PROCEDURE sp_LayDanhGiaSach_TheoSao
    @MaSach INT,
    @SoSaoToiThieu INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        DG.ma_khach_hang,
        KH.ho,
        KH.ho_ten_dem,
        DG.so_sao,
        DG.noi_dung,
        DG.ngay_danh_gia
    FROM danh_gia DG
    INNER JOIN khach_hang KH ON DG.ma_khach_hang = KH.ma_khach_hang    
    WHERE DG.ma_sach = @MaSach        
      AND DG.so_sao >= @SoSaoToiThieu 
    ORDER BY DG.ngay_danh_gia DESC;
END;
GO

-- ======================================================
-- 10. PROCEDURE: Add to Cart (Auto-create logic)
-- Overwrites any previous similar logic.
-- Logic:
--   1. Find active cart (Ordered=0, Cancelled=0).
--   2. If none, create new.
--   3. Get current book price.
--   4. Upsert item (Update qty if exists, else Insert).
--   5. Recalculate Cart Total.
-- ======================================================
CREATE OR ALTER PROCEDURE sp_ThemSachVaoGioHang
    @ma_khach_hang INT,
    @ma_sach INT,
    @so_luong INT
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;

        DECLARE @ma_don INT;
        DECLARE @gia_hien_tai MONEY;
        DECLARE @ma_gia_hien_tai INT;

        -- A. Validate Book & Get Price Snapshot
        SELECT @gia_hien_tai = gia_hien_tai, @ma_gia_hien_tai = ma_gia_hien_tai
        FROM sach WHERE ma_sach = @ma_sach AND da_xoa = 0;

        IF @gia_hien_tai IS NULL 
            THROW 50001, N'Sách không tồn tại hoặc đã bị xóa.', 1;

        -- B. Find Active Basket
        SELECT TOP 1 @ma_don = ma_don 
        FROM don_hang 
        WHERE ma_khach_hang = @ma_khach_hang 
          AND da_dat_hang = 0 
          AND da_huy = 0;

        -- C. Create New Basket if needed
        IF @ma_don IS NULL
        BEGIN
            INSERT INTO don_hang (ma_khach_hang, da_dat_hang, da_giao_hang, da_huy, tong_tien_thanh_toan)
            VALUES (@ma_khach_hang, 0, 0, 0, 0);
            
            SET @ma_don = SCOPE_IDENTITY();
        END

        -- D. Upsert Item (Add to Cart)
        IF EXISTS (SELECT 1 FROM chi_tiet_don_hang WHERE ma_don = @ma_don AND ma_sach = @ma_sach)
        BEGIN
            -- Item exists: Update Quantity & Refresh Price to current
            UPDATE chi_tiet_don_hang
            SET so_luong = so_luong + @so_luong,
                gia_ban = @gia_hien_tai,      -- Always refresh price in cart
                ma_gia = @ma_gia_hien_tai
            WHERE ma_don = @ma_don AND ma_sach = @ma_sach;
        END
        ELSE
        BEGIN
            -- Item new: Insert
            INSERT INTO chi_tiet_don_hang (ma_don, ma_sach, ma_gia, gia_ban, so_luong)
            VALUES (@ma_don, @ma_sach, @ma_gia_hien_tai, @gia_hien_tai, @so_luong);
        END

        -- E. Recalculate Cart Total
        DECLARE @TongTien MONEY;
        SELECT @TongTien = SUM(so_luong * gia_ban) 
        FROM chi_tiet_don_hang 
        WHERE ma_don = @ma_don;

        UPDATE don_hang SET tong_tien_thanh_toan = ISNULL(@TongTien, 0) WHERE ma_don = @ma_don;

        COMMIT TRANSACTION;
        
        -- Return Cart ID
        SELECT @ma_don AS ma_gio_hang;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO

-- ======================================================
-- 1. PROCEDURE: Remove Item from Cart
-- Logic: Finds active cart -> Deletes Item -> Recalculates Total
-- ======================================================
CREATE OR ALTER PROCEDURE sp_XoaKhoiGioHang
    @ma_khach_hang INT,
    @ma_sach INT
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;

        DECLARE @ma_don INT;

        -- 1. Find Active Basket
        SELECT TOP 1 @ma_don = ma_don 
        FROM don_hang 
        WHERE ma_khach_hang = @ma_khach_hang 
          AND da_dat_hang = 0 
          AND da_huy = 0;

        IF @ma_don IS NULL 
            THROW 50005, N'Không tìm thấy giỏ hàng đang hoạt động.', 1;

        -- 2. Delete the item
        DELETE FROM chi_tiet_don_hang 
        WHERE ma_don = @ma_don AND ma_sach = @ma_sach;

        -- 3. Recalculate Cart Total
        DECLARE @TongTien MONEY;
        SELECT @TongTien = SUM(so_luong * gia_ban) 
        FROM chi_tiet_don_hang 
        WHERE ma_don = @ma_don;

        UPDATE don_hang 
        SET tong_tien_thanh_toan = ISNULL(@TongTien, 0) 
        WHERE ma_don = @ma_don;

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO

-- ======================================================
-- 2. PROCEDURE: Update Cart Quantity
-- Logic: 
--   If Quantity <= 0 -> Delete Item.
--   If Quantity > 0  -> Update Qty AND Refresh Price (Price Trap Fix).
-- ======================================================
CREATE OR ALTER PROCEDURE sp_CapNhatSoLuongGioHang
    @ma_khach_hang INT,
    @ma_sach INT,
    @so_luong_moi INT
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;

        -- 1. If quantity is 0 or less, just call remove
        IF @so_luong_moi <= 0
        BEGIN
            EXEC sp_XoaKhoiGioHang @ma_khach_hang, @ma_sach;
            COMMIT TRANSACTION;
            RETURN;
        END

        DECLARE @ma_don INT;
        
        -- 2. Find Active Basket
        SELECT TOP 1 @ma_don = ma_don 
        FROM don_hang 
        WHERE ma_khach_hang = @ma_khach_hang 
          AND da_dat_hang = 0 
          AND da_huy = 0;

        IF @ma_don IS NULL 
            THROW 50005, N'Không tìm thấy giỏ hàng đang hoạt động.', 1;

        -- 3. Check if item exists in cart
        IF NOT EXISTS (SELECT 1 FROM chi_tiet_don_hang WHERE ma_don = @ma_don AND ma_sach = @ma_sach)
            THROW 50006, N'Sách này không có trong giỏ hàng.', 1;

        -- 4. Get Current Price (Refresh price on update to be fair)
        DECLARE @gia_hien_tai MONEY;
        DECLARE @ma_gia_hien_tai INT;
        
        SELECT @gia_hien_tai = gia_hien_tai, @ma_gia_hien_tai = ma_gia_hien_tai
        FROM sach WHERE ma_sach = @ma_sach;

        -- 5. Update Detail
        UPDATE chi_tiet_don_hang
        SET so_luong = @so_luong_moi,
            gia_ban = @gia_hien_tai,     -- Lock in new price
            ma_gia = @ma_gia_hien_tai
        WHERE ma_don = @ma_don AND ma_sach = @ma_sach;

        -- 6. Recalculate Cart Total
        DECLARE @TongTien MONEY;
        SELECT @TongTien = SUM(so_luong * gia_ban) 
        FROM chi_tiet_don_hang 
        WHERE ma_don = @ma_don;

        UPDATE don_hang 
        SET tong_tien_thanh_toan = ISNULL(@TongTien, 0) 
        WHERE ma_don = @ma_don;

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO

-- ======================================================
-- 2. PROCEDURE: Set Payment Method (Upsert)
-- Logic: 
--   1. Find Active Cart.
--   2. Check if Payment exists.
--   3. If yes, UPDATE method. If no, INSERT method.
-- ======================================================
CREATE OR ALTER PROCEDURE sp_ChonPhuongThucThanhToan
    @ma_khach_hang INT,
    @hinh_thuc NVARCHAR(50) -- 'Visa' or 'Shipper'
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;

        -- A. Find Active Cart
        DECLARE @ma_don INT;
        DECLARE @tong_tien MONEY;

        SELECT TOP 1 @ma_don = ma_don, @tong_tien = tong_tien_thanh_toan
        FROM don_hang 
        WHERE ma_khach_hang = @ma_khach_hang 
          AND da_dat_hang = 0 
          AND da_huy = 0;

        IF @ma_don IS NULL 
            THROW 50010, N'Bạn chưa có giỏ hàng để chọn thanh toán.', 1;

        -- B. Validate Method
        IF @hinh_thuc NOT IN ('Visa', 'Shipper')
            THROW 50011, N'Phương thức không hợp lệ (Chỉ chấp nhận: Visa, Shipper).', 1;

        -- C. Determine Status (Simulation)
        -- If 'Shipper' -> Pending. If 'Visa' -> Success (Simulated instant pay).
        DECLARE @status NVARCHAR(50) = 'Pending';
        IF @hinh_thuc = 'Visa' SET @status = 'Success';

        -- D. Upsert (Update if exists, Insert if not)
        MERGE thanh_toan AS target
        USING (SELECT @ma_don AS ma_don) AS source
        ON (target.ma_don = source.ma_don)
        WHEN MATCHED THEN
            UPDATE SET 
                hinh_thuc = @hinh_thuc,
                thanh_tien = @tong_tien,
                trinh_trang = @status
        WHEN NOT MATCHED THEN
            INSERT (ma_don, hinh_thuc, trinh_trang, thanh_tien)
            VALUES (@ma_don, @hinh_thuc, @status, @tong_tien);

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO

-- ======================================================
-- PROCEDURE: Get Last Payment Method
-- Logic: Find the latest Order (by ID) that has a Payment Record
-- ======================================================
CREATE OR ALTER PROCEDURE sp_LayThanhToanGanNhat
    @ma_khach_hang INT
AS
BEGIN
    SET NOCOUNT ON;

    -- Select the most recent payment method used by this customer
    SELECT TOP 1 tt.hinh_thuc
    FROM don_hang dh
    INNER JOIN thanh_toan tt ON dh.ma_don = tt.ma_don
    WHERE dh.ma_khach_hang = @ma_khach_hang
    ORDER BY dh.ma_don DESC; -- Latest one first
END;
GO

-- ======================================================
-- PROCEDURE: Apply Voucher to Cart
-- Logic:
--   1. Check if User owns voucher.
--   2. Loop through cart items.
--   3. Sum price of *ELIGIBLE* items only.
--   4. Calculate Discount.
--   5. Update Order 'gia_tri_giam_gia' & 'ma_voucher'.
-- ======================================================
CREATE OR ALTER PROCEDURE sp_ApDungVoucherVaoGioHang
    @ma_khach_hang INT,
    @ma_code NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;

        -- A. Find Active Cart
        DECLARE @ma_don INT;
        SELECT TOP 1 @ma_don = ma_don FROM don_hang 
        WHERE ma_khach_hang = @ma_khach_hang AND da_dat_hang = 0 AND da_huy = 0;

        IF @ma_don IS NULL THROW 50020, N'Không tìm thấy giỏ hàng.', 1;

        -- B. Find Voucher & Validate Ownership
        DECLARE @ma_voucher INT, @ma_nxb INT, @all_books BIT, @type NVARCHAR(20), @val DECIMAL(10,2), @max_disc MONEY;
        
        SELECT 
            @ma_voucher = v.ma_voucher,
            @ma_nxb = v.ma_nxb,
            @all_books = v.ap_dung_tat_ca_sach,
            @type = v.loai_giam,
            @val = v.gia_tri_giam,
            @max_disc = v.giam_toi_da
        FROM voucher v
        INNER JOIN voucher_thanh_vien vtv ON v.ma_voucher = vtv.ma_voucher
        WHERE v.ma_code = @ma_code 
          AND vtv.ma_khach_hang = @ma_khach_hang 
          AND vtv.so_luong > 0
          AND GETDATE() BETWEEN v.bat_dau AND v.ket_thuc;

        IF @ma_voucher IS NULL THROW 50021, N'Voucher không hợp lệ hoặc bạn không sở hữu.', 1;

        -- C. Calculate Total Eligible Amount in Cart
        DECLARE @TongTienDuDieuKien MONEY = 0;

        SELECT @TongTienDuDieuKien = SUM(ct.so_luong * ct.gia_ban)
        FROM chi_tiet_don_hang ct
        JOIN sach s ON ct.ma_sach = s.ma_sach
        WHERE ct.ma_don = @ma_don
          -- Rule 1: Check Publisher (If Voucher has specific NXB)
          AND (@ma_nxb IS NULL OR s.ma_nxb = @ma_nxb)
          -- Rule 2: Check Specific Books (If Voucher is not for all books)
          AND (@all_books = 1 OR EXISTS (SELECT 1 FROM voucher_sach vs WHERE vs.ma_voucher = @ma_voucher AND vs.ma_sach = s.ma_sach));

        IF @TongTienDuDieuKien IS NULL SET @TongTienDuDieuKien = 0;
        
        IF @TongTienDuDieuKien = 0 
            THROW 50022, N'Không có sản phẩm nào trong giỏ hàng phù hợp với voucher này.', 1;

        -- D. Calculate Discount
        DECLARE @GiamGia MONEY = 0;
        
        IF @type = N'Số tiền'
            SET @GiamGia = @val;
        ELSE -- 'Phần trăm'
            SET @GiamGia = @TongTienDuDieuKien * (@val / 100.0);

        -- Cap discount if max_disc is set
        IF @max_disc IS NOT NULL AND @GiamGia > @max_disc
            SET @GiamGia = @max_disc;

        -- Discount cannot exceed eligible total
        IF @GiamGia > @TongTienDuDieuKien
            SET @GiamGia = @TongTienDuDieuKien;

        -- E. Update Order
        UPDATE don_hang 
        SET ma_voucher = @ma_voucher, 
            gia_tri_giam_gia = @GiamGia 
        WHERE ma_don = @ma_don;

        COMMIT TRANSACTION;
        
        SELECT @GiamGia AS gia_tri_giam_duoc, @TongTienDuDieuKien as tong_tien_du_dk;
        
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO

-- ======================================================
-- 1. [NEW] ADDRESS SNAPSHOT PROCEDURE (For V5 Schema)
-- Logic: Copies address text from 'dia_chi_cu_the' to 'don_hang'
--        This "locks" the address so it doesn't change later.
-- ======================================================
CREATE OR ALTER PROCEDURE sp_ChonDiaChiGiaoHang
    @ma_khach_hang INT,
    @ma_dia_chi INT
AS
BEGIN
    SET NOCOUNT ON;
    
    -- A. Find Active Cart
    DECLARE @MaDon INT;
    SELECT TOP 1 @MaDon = ma_don FROM don_hang 
    WHERE ma_khach_hang = @ma_khach_hang AND da_dat_hang = 0 AND da_huy = 0;

    IF @MaDon IS NULL THROW 50001, N'Không tìm thấy giỏ hàng.', 1;

    -- B. Get Address String (Format: "123 Street, Ward, District, City")
    DECLARE @FullAddress NVARCHAR(500);
    SELECT @FullAddress = dia_chi_nha + ', ' + phuong_xa + ', ' + quan_huyen + ', ' + thanh_pho
    FROM dia_chi_cu_the
    WHERE ma_dia_chi = @ma_dia_chi AND ma_khach_hang = @ma_khach_hang;

    IF @FullAddress IS NULL THROW 50002, N'Địa chỉ không hợp lệ hoặc không thuộc về bạn.', 1;

    -- C. Update Order (Snapshot)
    UPDATE don_hang 
    SET dia_chi_giao_hang = @FullAddress 
    WHERE ma_don = @MaDon;
END;
GO

-- ======================================================
-- ADVANCED SEARCH
-- Logic: Filter Main Table first. 
--        Check Author/Category existence in subqueries.
-- ======================================================
CREATE OR ALTER PROCEDURE sp_TimKiemSach_NangCao
    @ten_sach NVARCHAR(200),           -- REQUIRED
    @ten_tac_gia NVARCHAR(200) = NULL, -- OPTIONAL
    @ten_the_loai NVARCHAR(200) = NULL -- OPTIONAL
AS
BEGIN
    SET NOCOUNT ON;

    -- 1. Validate Required Input
    IF @ten_sach IS NULL OR LTRIM(RTRIM(@ten_sach)) = ''
    BEGIN
        RAISERROR(N'Tên sách không được để trống.', 16, 1);
        RETURN;
    END

    -- 2. Execute Search
    -- Note: We removed DISTINCT because we are not joining the many-to-many tables directly.
    SELECT 
        s.ma_sach,
        s.ten_sach,
        s.gia_hien_tai,
        s.so_sao_trung_binh,
        nxb.ten_nxb,
        s.nam_xuat_ban,
        s.hinh_thuc
    FROM sach s
    JOIN nha_xuat_ban nxb ON s.ma_nxb = nxb.ma_nxb
    WHERE 
        s.da_xoa = 0
        -- A. Name Match (Required)
        AND s.ten_sach LIKE N'%' + @ten_sach + N'%'
        
        -- B. Author Match (Optional - Check Existence)
        AND (@ten_tac_gia IS NULL OR EXISTS (
            SELECT 1 
            FROM sach_tac_gia stg
            JOIN tac_gia tg ON stg.ma_tg = tg.ma_tg
            WHERE stg.ma_sach = s.ma_sach 
              AND tg.ten_tg LIKE N'%' + @ten_tac_gia + N'%'
        ))
        
        -- C. Category Match (Optional - Check Existence)
        AND (@ten_the_loai IS NULL OR EXISTS (
            SELECT 1 
            FROM sach_the_loai stl
            JOIN the_loai tl ON stl.ma_tl = tl.ma_tl
            WHERE stl.ma_sach = s.ma_sach 
              AND tl.ten_tl LIKE N'%' + @ten_the_loai + N'%'
        ))
    ORDER BY s.gia_hien_tai DESC;
END;
GO

-- ======================================================
-- 3. [NEW] AUTHOR STATS SEARCH (Assignment Req 2.3b)
-- Logic: Uses Aggregate (COUNT), GROUP BY, HAVING
-- ======================================================
CREATE OR ALTER PROCEDURE sp_TimKiemTacGia_ThongKe
    @keyword NVARCHAR(200) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        tg.ma_tg,
        tg.ten_tg,
        tg.quoc_tich,
        COUNT(s.ma_sach) AS so_luong_sach
    FROM tac_gia tg
    LEFT JOIN sach_tac_gia stg ON tg.ma_tg = stg.ma_tg
    LEFT JOIN sach s ON stg.ma_sach = s.ma_sach AND s.da_xoa = 0
    WHERE 
        (@keyword IS NULL OR tg.ten_tg LIKE N'%' + @keyword + N'%')
    GROUP BY 
        tg.ma_tg, tg.ten_tg, tg.quoc_tich
    HAVING 
        COUNT(s.ma_sach) >= 0 
    ORDER BY 
        so_luong_sach DESC;
END;
GO

PRINT N'All Procedures updated successfully!';
GO
